//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhereIsMyCursor.Resources {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WhereIsMyCursor.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 WhereIsMyCursor 的當地語系化字串。
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 開機時自動啟動 的當地語系化字串。
        /// </summary>
        public static string AutoStart {
            get {
                return ResourceManager.GetString("AutoStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 取消 的當地語系化字串。
        /// </summary>
        public static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 確定 的當地語系化字串。
        /// </summary>
        public static string ButtonOK {
            get {
                return ResourceManager.GetString("ButtonOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 啟用閃爍效果 (近距離閃爍提示) 的當地語系化字串。
        /// </summary>
        public static string EnableBlink {
            get {
                return ResourceManager.GetString("EnableBlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 高 (30 FPS，流暢) 的當地語系化字串。
        /// </summary>
        public static string FrequencyHigh {
            get {
                return ResourceManager.GetString("FrequencyHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 低 (2 FPS，省電) 的當地語系化字串。
        /// </summary>
        public static string FrequencyLow {
            get {
                return ResourceManager.GetString("FrequencyLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 中 (10 FPS，建議) 的當地語系化字串。
        /// </summary>
        public static string FrequencyMedium {
            get {
                return ResourceManager.GetString("FrequencyMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 語言： 的當地語系化字串。
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 結束 的當地語系化字串。
        /// </summary>
        public static string MenuExit {
            get {
                return ResourceManager.GetString("MenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 設定... 的當地語系化字串。
        /// </summary>
        public static string MenuSettings {
            get {
                return ResourceManager.GetString("MenuSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 X 偏移 (右→左)： 的當地語系化字串。
        /// </summary>
        public static string OffsetX {
            get {
                return ResourceManager.GetString("OffsetX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Y 偏移 (上→下)： 的當地語系化字串。
        /// </summary>
        public static string OffsetY {
            get {
                return ResourceManager.GetString("OffsetY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  px 的當地語系化字串。
        /// </summary>
        public static string PixelUnit {
            get {
                return ResourceManager.GetString("PixelUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 托盤圖示位置校正 的當地語系化字串。
        /// </summary>
        public static string PositionCalibration {
            get {
                return ResourceManager.GetString("PositionCalibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 提示：若箭頭方向不準確，請調整偏移值直到箭頭正確指向托盤圖示 的當地語系化字串。
        /// </summary>
        public static string PositionHint {
            get {
                return ResourceManager.GetString("PositionHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 動態托盤圖示設定 的當地語系化字串。
        /// </summary>
        public static string SettingsHeader {
            get {
                return ResourceManager.GetString("SettingsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 設定 - WhereIsMyCursor 的當地語系化字串。
        /// </summary>
        public static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 WhereIsMyCursor - 游標位置指示器 的當地語系化字串。
        /// </summary>
        public static string TrayTooltip {
            get {
                return ResourceManager.GetString("TrayTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 更新頻率： 的當地語系化字串。
        /// </summary>
        public static string UpdateFrequency {
            get {
                return ResourceManager.GetString("UpdateFrequency", resourceCulture);
            }
        }
    }
}
